### ISSUE TITLE
Pocket should allow the plugins to implement their own sendTransaction and executeQuery

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-ios-sdk#26]
Allowing the plugins to do so will let the plugin developer add anything additional data to the flow. At the end the mobile developer will only call the plugin for the wallet, query and transaction logic, eg: PocketEth....

**Comment by luyzdeleon** [comment]
Closing this issue because every Plugin has the ability to expose their own methods to send transactions and executing queries by leveraging the current functionality.
