### ISSUE TITLE
Define "Plug-In" System

### ISSUE THREAD

**Issue by ArtSabintsev** [pokt-network/pocket-ios-sdk#4]
Provides a single common Plug-In interface to all blockchains that can integrate with the Pocket network. Plugins that define the cryptography needed for each individual network. Facilitates creation of Transaction and Query instances. Parses TransactionResponse and QueryResponse models

- [x] Implement PocketContextProtocol with an init function that receives a handler with a PocketProtocol instance as it's parameter.

**Comment by pabelnl** [comment]
Changes available in branch plugin-definition
